/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CommunityProfile {
  'bio' : string,
  'seekingMentorship' : boolean,
  'displayName' : string,
  'profilePhoto' : [] | [ExternalBlob],
  'tags' : Array<string>,
  'pronouns' : string,
  'openToMentoring' : boolean,
  'supporterOfCommunity' : boolean,
  'avatar' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export interface HelloCornerMessage {
  'id' : MessageId,
  'video' : [] | [ExternalBlob],
  'createdAt' : bigint,
  'text' : string,
  'author' : Principal,
  'photo' : [] | [ExternalBlob],
}
export type MessageId = bigint;
export interface PaginatedMessages {
  'nextOffset' : bigint,
  'hasMore' : boolean,
  'messages' : Array<HelloCornerMessage>,
}
export type ReactionType = { 'like' : null } |
  { 'dislike' : null };
export type ReasonType = { 'violation' : null } |
  { 'troll' : null } |
  { 'other' : string } |
  { 'lecture' : null } |
  { 'insensitive' : null } |
  { 'offTopic' : null };
export interface Report {
  'id' : ReportId,
  'status' : ReportStatus,
  'contentId' : string,
  'reasonType' : ReasonType,
  'description' : string,
  'reportType' : ReportType,
  'timestamp' : bigint,
  'reporter' : Principal,
}
export type ReportId = bigint;
export type ReportStatus = { 'pending' : null } |
  { 'reviewed' : null };
export type ReportType = { 'message' : null } |
  { 'profile' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptContact' : ActorMethod<[Principal], undefined>,
  'addContact' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[Principal, string], undefined>,
  'browseMentors' : ActorMethod<
    [
      {
        'supporterOfCommunity' : boolean,
        'mentorship' : boolean,
        'mentoring' : boolean,
      },
    ],
    Array<CommunityProfile>
  >,
  'confirmEligibility' : ActorMethod<[], undefined>,
  'createHelloCornerMessage' : ActorMethod<
    [string, [] | [ExternalBlob], [] | [ExternalBlob]],
    MessageId
  >,
  'getBanReason' : ActorMethod<[Principal], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommunityProfile' : ActorMethod<[Principal], CommunityProfile>,
  'getContacts' : ActorMethod<[Principal], Array<Principal>>,
  'getLectureReports' : ActorMethod<[bigint, bigint], Array<Report>>,
  'getMessageReactions' : ActorMethod<
    [MessageId],
    { 'dislikeCount' : bigint, 'likeCount' : bigint }
  >,
  'getPendingTrollReports' : ActorMethod<
    [bigint, bigint],
    { 'pendingTrollReports' : Array<Report>, 'totalCount' : bigint }
  >,
  'getProfilePhoto' : ActorMethod<[Principal], [] | [ExternalBlob]>,
  'getReport' : ActorMethod<[ReportId], Report>,
  'getUserReportStats' : ActorMethod<
    [Principal],
    { 'profileReportCount' : bigint, 'messageReportCount' : bigint }
  >,
  'hasConfirmedEligibility' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserBannedForAdminCheck' : ActorMethod<[Principal], boolean>,
  'listHelloCornerMessages' : ActorMethod<[bigint, bigint], PaginatedMessages>,
  'listReports' : ActorMethod<[bigint, bigint], Array<Report>>,
  'reactToMessage' : ActorMethod<[MessageId, ReactionType], undefined>,
  'removeReaction' : ActorMethod<[MessageId], undefined>,
  'reportContent' : ActorMethod<
    [string, ReportType, ReasonType, string],
    undefined
  >,
  'resolveReport' : ActorMethod<[ReportId], undefined>,
  'unbanUser' : ActorMethod<[Principal], undefined>,
  'updateCommunityProfile' : ActorMethod<[CommunityProfile], undefined>,
  'uploadProfilePhoto' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];