/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CommunityProfile = IDL.Record({
  'bio' : IDL.Text,
  'seekingMentorship' : IDL.Bool,
  'displayName' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'tags' : IDL.Vec(IDL.Text),
  'pronouns' : IDL.Text,
  'openToMentoring' : IDL.Bool,
  'supporterOfCommunity' : IDL.Bool,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const MessageId = IDL.Nat;
export const ReportId = IDL.Nat;
export const ReportStatus = IDL.Variant({
  'pending' : IDL.Null,
  'reviewed' : IDL.Null,
});
export const ReasonType = IDL.Variant({
  'violation' : IDL.Null,
  'troll' : IDL.Null,
  'other' : IDL.Text,
  'lecture' : IDL.Null,
  'insensitive' : IDL.Null,
  'offTopic' : IDL.Null,
});
export const ReportType = IDL.Variant({
  'message' : IDL.Null,
  'profile' : IDL.Null,
});
export const Report = IDL.Record({
  'id' : ReportId,
  'status' : ReportStatus,
  'contentId' : IDL.Text,
  'reasonType' : ReasonType,
  'description' : IDL.Text,
  'reportType' : ReportType,
  'timestamp' : IDL.Int,
  'reporter' : IDL.Principal,
});
export const HelloCornerMessage = IDL.Record({
  'id' : MessageId,
  'video' : IDL.Opt(ExternalBlob),
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'photo' : IDL.Opt(ExternalBlob),
});
export const PaginatedMessages = IDL.Record({
  'nextOffset' : IDL.Nat,
  'hasMore' : IDL.Bool,
  'messages' : IDL.Vec(HelloCornerMessage),
});
export const ReactionType = IDL.Variant({
  'like' : IDL.Null,
  'dislike' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptContact' : IDL.Func([IDL.Principal], [], []),
  'addContact' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'browseMentors' : IDL.Func(
      [
        IDL.Record({
          'supporterOfCommunity' : IDL.Bool,
          'mentorship' : IDL.Bool,
          'mentoring' : IDL.Bool,
        }),
      ],
      [IDL.Vec(CommunityProfile)],
      ['query'],
    ),
  'confirmEligibility' : IDL.Func([], [], []),
  'createHelloCornerMessage' : IDL.Func(
      [IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(ExternalBlob)],
      [MessageId],
      [],
    ),
  'getBanReason' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommunityProfile' : IDL.Func(
      [IDL.Principal],
      [CommunityProfile],
      ['query'],
    ),
  'getContacts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getLectureReports' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Report)],
      ['query'],
    ),
  'getMessageReactions' : IDL.Func(
      [MessageId],
      [IDL.Record({ 'dislikeCount' : IDL.Nat, 'likeCount' : IDL.Nat })],
      ['query'],
    ),
  'getPendingTrollReports' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [
        IDL.Record({
          'pendingTrollReports' : IDL.Vec(Report),
          'totalCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getProfilePhoto' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getReport' : IDL.Func([ReportId], [Report], ['query']),
  'getUserReportStats' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'profileReportCount' : IDL.Nat,
          'messageReportCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'hasConfirmedEligibility' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserBannedForAdminCheck' : IDL.Func(
      [IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'listHelloCornerMessages' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [PaginatedMessages],
      ['query'],
    ),
  'listReports' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Report)], ['query']),
  'reactToMessage' : IDL.Func([MessageId, ReactionType], [], []),
  'removeReaction' : IDL.Func([MessageId], [], []),
  'reportContent' : IDL.Func(
      [IDL.Text, ReportType, ReasonType, IDL.Text],
      [],
      [],
    ),
  'resolveReport' : IDL.Func([ReportId], [], []),
  'unbanUser' : IDL.Func([IDL.Principal], [], []),
  'updateCommunityProfile' : IDL.Func([CommunityProfile], [], []),
  'uploadProfilePhoto' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CommunityProfile = IDL.Record({
    'bio' : IDL.Text,
    'seekingMentorship' : IDL.Bool,
    'displayName' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'tags' : IDL.Vec(IDL.Text),
    'pronouns' : IDL.Text,
    'openToMentoring' : IDL.Bool,
    'supporterOfCommunity' : IDL.Bool,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const MessageId = IDL.Nat;
  const ReportId = IDL.Nat;
  const ReportStatus = IDL.Variant({
    'pending' : IDL.Null,
    'reviewed' : IDL.Null,
  });
  const ReasonType = IDL.Variant({
    'violation' : IDL.Null,
    'troll' : IDL.Null,
    'other' : IDL.Text,
    'lecture' : IDL.Null,
    'insensitive' : IDL.Null,
    'offTopic' : IDL.Null,
  });
  const ReportType = IDL.Variant({
    'message' : IDL.Null,
    'profile' : IDL.Null,
  });
  const Report = IDL.Record({
    'id' : ReportId,
    'status' : ReportStatus,
    'contentId' : IDL.Text,
    'reasonType' : ReasonType,
    'description' : IDL.Text,
    'reportType' : ReportType,
    'timestamp' : IDL.Int,
    'reporter' : IDL.Principal,
  });
  const HelloCornerMessage = IDL.Record({
    'id' : MessageId,
    'video' : IDL.Opt(ExternalBlob),
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const PaginatedMessages = IDL.Record({
    'nextOffset' : IDL.Nat,
    'hasMore' : IDL.Bool,
    'messages' : IDL.Vec(HelloCornerMessage),
  });
  const ReactionType = IDL.Variant({ 'like' : IDL.Null, 'dislike' : IDL.Null });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptContact' : IDL.Func([IDL.Principal], [], []),
    'addContact' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'browseMentors' : IDL.Func(
        [
          IDL.Record({
            'supporterOfCommunity' : IDL.Bool,
            'mentorship' : IDL.Bool,
            'mentoring' : IDL.Bool,
          }),
        ],
        [IDL.Vec(CommunityProfile)],
        ['query'],
      ),
    'confirmEligibility' : IDL.Func([], [], []),
    'createHelloCornerMessage' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(ExternalBlob)],
        [MessageId],
        [],
      ),
    'getBanReason' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommunityProfile' : IDL.Func(
        [IDL.Principal],
        [CommunityProfile],
        ['query'],
      ),
    'getContacts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getLectureReports' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Report)],
        ['query'],
      ),
    'getMessageReactions' : IDL.Func(
        [MessageId],
        [IDL.Record({ 'dislikeCount' : IDL.Nat, 'likeCount' : IDL.Nat })],
        ['query'],
      ),
    'getPendingTrollReports' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [
          IDL.Record({
            'pendingTrollReports' : IDL.Vec(Report),
            'totalCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getProfilePhoto' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getReport' : IDL.Func([ReportId], [Report], ['query']),
    'getUserReportStats' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'profileReportCount' : IDL.Nat,
            'messageReportCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'hasConfirmedEligibility' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserBannedForAdminCheck' : IDL.Func(
        [IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'listHelloCornerMessages' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [PaginatedMessages],
        ['query'],
      ),
    'listReports' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Report)], ['query']),
    'reactToMessage' : IDL.Func([MessageId, ReactionType], [], []),
    'removeReaction' : IDL.Func([MessageId], [], []),
    'reportContent' : IDL.Func(
        [IDL.Text, ReportType, ReasonType, IDL.Text],
        [],
        [],
      ),
    'resolveReport' : IDL.Func([ReportId], [], []),
    'unbanUser' : IDL.Func([IDL.Principal], [], []),
    'updateCommunityProfile' : IDL.Func([CommunityProfile], [], []),
    'uploadProfilePhoto' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };