/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConnectionRequest {
  'to' : Principal,
  'from' : Principal,
  'timestamp' : bigint,
}
export interface ConnectionsReply {
  'id' : ReplyId,
  'content' : string,
  'createdAt' : bigint,
  'author' : Principal,
  'threadId' : ThreadId,
}
export interface ConnectionsThread {
  'id' : ThreadId,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'author' : Principal,
  'isVisible' : boolean,
  'replies' : Array<ConnectionsReply>,
}
export type ReplyId = bigint;
export type ThreadId = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptConnectionRequest' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createThread' : ActorMethod<[string, string], ThreadId>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPendingConnectionRequests' : ActorMethod<[], Array<ConnectionRequest>>,
  'getThread' : ActorMethod<[ThreadId], ConnectionsThread>,
  'getThreadReplies' : ActorMethod<[ThreadId], Array<ConnectionsReply>>,
  'getUserConnections' : ActorMethod<[Principal], Array<Principal>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listThreads' : ActorMethod<[bigint, bigint], Array<ConnectionsThread>>,
  'replyToThread' : ActorMethod<[ThreadId, string], ReplyId>,
  'sendConnectionRequest' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];