/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ThreadId = IDL.Nat;
export const ConnectionRequest = IDL.Record({
  'to' : IDL.Principal,
  'from' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const ReplyId = IDL.Nat;
export const ConnectionsReply = IDL.Record({
  'id' : ReplyId,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'author' : IDL.Principal,
  'threadId' : ThreadId,
});
export const ConnectionsThread = IDL.Record({
  'id' : ThreadId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'author' : IDL.Principal,
  'isVisible' : IDL.Bool,
  'replies' : IDL.Vec(ConnectionsReply),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptConnectionRequest' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createThread' : IDL.Func([IDL.Text, IDL.Text], [ThreadId], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPendingConnectionRequests' : IDL.Func(
      [],
      [IDL.Vec(ConnectionRequest)],
      ['query'],
    ),
  'getThread' : IDL.Func([ThreadId], [ConnectionsThread], ['query']),
  'getThreadReplies' : IDL.Func(
      [ThreadId],
      [IDL.Vec(ConnectionsReply)],
      ['query'],
    ),
  'getUserConnections' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listThreads' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ConnectionsThread)],
      ['query'],
    ),
  'replyToThread' : IDL.Func([ThreadId, IDL.Text], [ReplyId], []),
  'sendConnectionRequest' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ThreadId = IDL.Nat;
  const ConnectionRequest = IDL.Record({
    'to' : IDL.Principal,
    'from' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const ReplyId = IDL.Nat;
  const ConnectionsReply = IDL.Record({
    'id' : ReplyId,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'author' : IDL.Principal,
    'threadId' : ThreadId,
  });
  const ConnectionsThread = IDL.Record({
    'id' : ThreadId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'author' : IDL.Principal,
    'isVisible' : IDL.Bool,
    'replies' : IDL.Vec(ConnectionsReply),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptConnectionRequest' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createThread' : IDL.Func([IDL.Text, IDL.Text], [ThreadId], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPendingConnectionRequests' : IDL.Func(
        [],
        [IDL.Vec(ConnectionRequest)],
        ['query'],
      ),
    'getThread' : IDL.Func([ThreadId], [ConnectionsThread], ['query']),
    'getThreadReplies' : IDL.Func(
        [ThreadId],
        [IDL.Vec(ConnectionsReply)],
        ['query'],
      ),
    'getUserConnections' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listThreads' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ConnectionsThread)],
        ['query'],
      ),
    'replyToThread' : IDL.Func([ThreadId, IDL.Text], [ReplyId], []),
    'sendConnectionRequest' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };